parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        dbname:               '%env(RDS_DB_NAME)%'
        host:                 '%env(RDS_HOSTNAME)%'
        port:                 '%env(RDS_PORT)%'
        user:                 '%env(RDS_USERNAME)%'
        password:             '%env(RDS_PASSWORD)%'
        driver:               '%env(RDS_DRIVER)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
