framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: false

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: PLUS
        cookie_lifetime: 86400
        gc_maxlifetime: 1800

    templating:
        engines: ['twig']

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: ewebify/papalocal

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

    ## Buses
    messenger:
        default_bus: messenger.bus.application

        buses:
            messenger.bus.application:
                middleware:
                    - 'messenger.middleware.validation'
            messenger.bus.mysql:
                middleware:
                    - 'messenger.middleware.validation'
            messenger.bus.notification: ~