monolog:
#    handlers:
#        main:
#            type: fingers_crossed
#            action_level: error
#            handler: nested
#            excluded_404s:
#                # regex: exclude all 404 errors from the logs
#                - ^/
#        nested:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
    handlers:
        finger_crossed:
            type: fingers_crossed
            # 500 errors are logged at the critical level
            buffer_size: 30
            # to also log 400 level errors (but not 404's):
            excluded_404s:
                - ^/(.)+
            handler: mysql
            channels: ['!event', '!console', '!doctrine']
        mysql:
            type: service
            id: monolog.handler.database
            level: debug
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
