security:
# https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        PapaLocal\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
    #            encode_as_base64: true
    #            iterations: 5000

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_provider:
            id: papalocal_data.user_provider

    role_hierarchy:
        ROLE_REFERRAL_PARTNER: ROLE_USER
        ROLE_COMPANY: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # primary firewall
        main:
            pattern: ^/
            anonymous: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                provider: database_provider
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: (^/login|register|forgot-password|reset-password|process-password-reset|terms-of-service$)|(agreement\/referral\/join), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/api)(.)+$, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }